### ISSUE TITLE
How to change the size of icons and empty place between them correctly?

### ISSUE THREAD

**Issue by gerchicov-bp** [heikomaass/HMLauncherView#10]
I want to decrease the empty place and increase the size of views but I can't adjust it correctly for dragging: it operates with other areas.
Could you explain how to fix it?

**Comment by heikomaass** [comment]
The dimensions are fetched from the `HMLauncherDataSource.buttonDimensionsInLauncherView` method. Here you can define the size of an icon as CGSize.

The space between the icons will be calculated in the `HMLauncherView.calculateIconSpacer` method using the bounds of the view and the icon size from the delegate.
