### ISSUE TITLE
Unable to compile and run HMLauncherViewExample

### ISSUE THREAD

**Issue by jsubida** [heikomaass/HMLauncherView#2]
Hi there. I get 7 errors when I open and try to run HMLauncherViewExample. 5 of these errors state that HMLauncher\* files cannot be found. The other 2:
1.  `error: unable to open executable '/Users/JC/Library/Developer/Xcode/DerivedData/HMLauncherViewExample-avwfkwtnfczafkgndwfteeqtpovv/Build/Products/Debug-iphonesimulator/HMLauncherViewExample.app/HMLauncherViewExample'`
2. `Linker command failed with exit code 1 (use -v to see invocation)`

How can I fix this?

**Comment by jsubida** [comment]
Checking out the code using Git breaks it. However, downloading the zip file allows me to run the HMLauncherViewExample.

**Comment by heikomaass** [comment]
Strange. I've cloned the repository on several macs, and never encountered this issue. 

Perhaps the following stackoverflow answers might help you:
http://stackoverflow.com/questions/8746194/unable-to-open-executable-xcode
http://stackoverflow.com/a/8345987

**Comment by jsubida** [comment]
Ah. I wrote a response on cocoacontrols.com. I forgot to post it here, too.

http://cocoacontrols.com/platforms/ios/controls/hmlauncherview

**Comment by heikomaass** [comment]
Hello, JSubida,

thanks for your detailed error description. I've added quotation marks in the header path.

Cheers,

Heiko
