### ISSUE TITLE
Shaking doesn't stop automatically, sometimes

### ISSUE THREAD

**Issue by ghulammustafa** [heikomaass/HMLauncherView#5]
Sometimes, when a HMLauncherIcon is moved from one view to another, the shaking doesn't stop. I think it has something to do with the speed of the operation (move operation).

It would be nice to have a feature that allows the users to change the state of the view to "Editing" and "Done Editing". During this state, user can perform multiple edit operations i.e. Deletions.

**Comment by heikomaass** [comment]
Hi,

regarding the first issue: 
--> I need some more time to investigate. 

regarding the editing and done editing state:
This is already possible, just put your criteria in the `launcherViewShouldStopEditingAfterDraggingEnds` of the `HMLauncherViewDelegate` protocol.

`- (BOOL) launcherViewShouldStopEditingAfterDraggingEnds:(HMLauncherView *)launcherView {
   return yourShouldStopEditingCriteria;
}`
