### ISSUE TITLE
How to set active page manually?

### ISSUE THREAD

**Issue by xzenon** [heikomaass/HMLauncherView#7]
Hi! Thanks for the great work on such useful launcher view.
Have a question - how to set initial page for launcher view manually? I just want to set second (not the first) page to be active when launcher become visible initially. Is it possible?

**Comment by heikomaass** [comment]
With the last commit (0bc0902fc59f7518dc897bb43ccca48af680abc6) I've introduced the following new methods on HMLauncherView:
- setCurrentPage:(NSUInteger) animated:(BOOL)
- currentPage

**Comment by xzenon** [comment]
Thanks a lot!

**Comment by heikomaass** [comment]
You're welcome :)
